/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCateringRouteImport } from './routes/_authenticated/catering'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedDanceRouteImport } from './routes/_authenticated/dance'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedGuestsRouteImport } from './routes/_authenticated/guests'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHotelRouteImport } from './routes/_authenticated/hotel'
import { Route as AuthenticatedJewelleryRouteImport } from './routes/_authenticated/jewellery'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedMusicRouteImport } from './routes/_authenticated/music'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedOutfitsRouteImport } from './routes/_authenticated/outfits'
import { Route as AuthenticatedPackingRouteImport } from './routes/_authenticated/packing'
import { Route as AuthenticatedPhotoChecklistRouteImport } from './routes/_authenticated/photo-checklist'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedPujaRouteImport } from './routes/_authenticated/puja'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedReturnGiftsRouteImport } from './routes/_authenticated/return-gifts'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSeatingRouteImport } from './routes/_authenticated/seating'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedTravelRouteImport } from './routes/_authenticated/travel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCateringRoute = AuthenticatedCateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDanceRoute = AuthenticatedDanceRouteImport.update({
  id: '/dance',
  path: '/dance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuestsRoute = AuthenticatedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotelRoute = AuthenticatedHotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJewelleryRoute = AuthenticatedJewelleryRouteImport.update({
  id: '/jewellery',
  path: '/jewellery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicRoute = AuthenticatedMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutfitsRoute = AuthenticatedOutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackingRoute = AuthenticatedPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPhotoChecklistRoute =
  AuthenticatedPhotoChecklistRouteImport.update({
    id: '/photo-checklist',
    path: '/photo-checklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPujaRoute = AuthenticatedPujaRouteImport.update({
  id: '/puja',
  path: '/puja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnGiftsRoute =
  AuthenticatedReturnGiftsRouteImport.update({
    id: '/return-gifts',
    path: '/return-gifts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeatingRoute = AuthenticatedSeatingRouteImport.update({
  id: '/seating',
  path: '/seating',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTravelRoute = AuthenticatedTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/catering': typeof AuthenticatedCateringRoute
  '/chat': typeof AuthenticatedChatRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dance': typeof AuthenticatedDanceRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/hotel': typeof AuthenticatedHotelRoute
  '/jewellery': typeof AuthenticatedJewelleryRoute
  '/live': typeof AuthenticatedLiveRoute
  '/music': typeof AuthenticatedMusicRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/outfits': typeof AuthenticatedOutfitsRoute
  '/packing': typeof AuthenticatedPackingRoute
  '/photo-checklist': typeof AuthenticatedPhotoChecklistRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/puja': typeof AuthenticatedPujaRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/return-gifts': typeof AuthenticatedReturnGiftsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/search': typeof AuthenticatedSearchRoute
  '/seating': typeof AuthenticatedSeatingRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/travel': typeof AuthenticatedTravelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/catering': typeof AuthenticatedCateringRoute
  '/chat': typeof AuthenticatedChatRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dance': typeof AuthenticatedDanceRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/guests': typeof AuthenticatedGuestsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/hotel': typeof AuthenticatedHotelRoute
  '/jewellery': typeof AuthenticatedJewelleryRoute
  '/live': typeof AuthenticatedLiveRoute
  '/music': typeof AuthenticatedMusicRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/outfits': typeof AuthenticatedOutfitsRoute
  '/packing': typeof AuthenticatedPackingRoute
  '/photo-checklist': typeof AuthenticatedPhotoChecklistRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/puja': typeof AuthenticatedPujaRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/return-gifts': typeof AuthenticatedReturnGiftsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/search': typeof AuthenticatedSearchRoute
  '/seating': typeof AuthenticatedSeatingRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/travel': typeof AuthenticatedTravelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/catering': typeof AuthenticatedCateringRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dance': typeof AuthenticatedDanceRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/guests': typeof AuthenticatedGuestsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/hotel': typeof AuthenticatedHotelRoute
  '/_authenticated/jewellery': typeof AuthenticatedJewelleryRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/music': typeof AuthenticatedMusicRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/outfits': typeof AuthenticatedOutfitsRoute
  '/_authenticated/packing': typeof AuthenticatedPackingRoute
  '/_authenticated/photo-checklist': typeof AuthenticatedPhotoChecklistRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/puja': typeof AuthenticatedPujaRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/return-gifts': typeof AuthenticatedReturnGiftsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/seating': typeof AuthenticatedSeatingRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/travel': typeof AuthenticatedTravelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/budget'
    | '/calendar'
    | '/catering'
    | '/chat'
    | '/checklist'
    | '/contacts'
    | '/dance'
    | '/documents'
    | '/family'
    | '/gallery'
    | '/guests'
    | '/home'
    | '/hotel'
    | '/jewellery'
    | '/live'
    | '/music'
    | '/notes'
    | '/outfits'
    | '/packing'
    | '/photo-checklist'
    | '/progress'
    | '/providers'
    | '/puja'
    | '/reminders'
    | '/return-gifts'
    | '/schedule'
    | '/search'
    | '/seating'
    | '/tasks'
    | '/today'
    | '/travel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/budget'
    | '/calendar'
    | '/catering'
    | '/chat'
    | '/checklist'
    | '/contacts'
    | '/dance'
    | '/documents'
    | '/family'
    | '/gallery'
    | '/guests'
    | '/home'
    | '/hotel'
    | '/jewellery'
    | '/live'
    | '/music'
    | '/notes'
    | '/outfits'
    | '/packing'
    | '/photo-checklist'
    | '/progress'
    | '/providers'
    | '/puja'
    | '/reminders'
    | '/return-gifts'
    | '/schedule'
    | '/search'
    | '/seating'
    | '/tasks'
    | '/today'
    | '/travel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/budget'
    | '/_authenticated/calendar'
    | '/_authenticated/catering'
    | '/_authenticated/chat'
    | '/_authenticated/checklist'
    | '/_authenticated/contacts'
    | '/_authenticated/dance'
    | '/_authenticated/documents'
    | '/_authenticated/family'
    | '/_authenticated/gallery'
    | '/_authenticated/guests'
    | '/_authenticated/home'
    | '/_authenticated/hotel'
    | '/_authenticated/jewellery'
    | '/_authenticated/live'
    | '/_authenticated/music'
    | '/_authenticated/notes'
    | '/_authenticated/outfits'
    | '/_authenticated/packing'
    | '/_authenticated/photo-checklist'
    | '/_authenticated/progress'
    | '/_authenticated/providers'
    | '/_authenticated/puja'
    | '/_authenticated/reminders'
    | '/_authenticated/return-gifts'
    | '/_authenticated/schedule'
    | '/_authenticated/search'
    | '/_authenticated/seating'
    | '/_authenticated/tasks'
    | '/_authenticated/today'
    | '/_authenticated/travel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catering': {
      id: '/_authenticated/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof AuthenticatedCateringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dance': {
      id: '/_authenticated/dance'
      path: '/dance'
      fullPath: '/dance'
      preLoaderRoute: typeof AuthenticatedDanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guests': {
      id: '/_authenticated/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AuthenticatedGuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotel': {
      id: '/_authenticated/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof AuthenticatedHotelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jewellery': {
      id: '/_authenticated/jewellery'
      path: '/jewellery'
      fullPath: '/jewellery'
      preLoaderRoute: typeof AuthenticatedJewelleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/music': {
      id: '/_authenticated/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof AuthenticatedMusicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outfits': {
      id: '/_authenticated/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof AuthenticatedOutfitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packing': {
      id: '/_authenticated/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof AuthenticatedPackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/photo-checklist': {
      id: '/_authenticated/photo-checklist'
      path: '/photo-checklist'
      fullPath: '/photo-checklist'
      preLoaderRoute: typeof AuthenticatedPhotoChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/puja': {
      id: '/_authenticated/puja'
      path: '/puja'
      fullPath: '/puja'
      preLoaderRoute: typeof AuthenticatedPujaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/return-gifts': {
      id: '/_authenticated/return-gifts'
      path: '/return-gifts'
      fullPath: '/return-gifts'
      preLoaderRoute: typeof AuthenticatedReturnGiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seating': {
      id: '/_authenticated/seating'
      path: '/seating'
      fullPath: '/seating'
      preLoaderRoute: typeof AuthenticatedSeatingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/travel': {
      id: '/_authenticated/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof AuthenticatedTravelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCateringRoute: typeof AuthenticatedCateringRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDanceRoute: typeof AuthenticatedDanceRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedGuestsRoute: typeof AuthenticatedGuestsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedHotelRoute: typeof AuthenticatedHotelRoute
  AuthenticatedJewelleryRoute: typeof AuthenticatedJewelleryRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMusicRoute: typeof AuthenticatedMusicRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedOutfitsRoute: typeof AuthenticatedOutfitsRoute
  AuthenticatedPackingRoute: typeof AuthenticatedPackingRoute
  AuthenticatedPhotoChecklistRoute: typeof AuthenticatedPhotoChecklistRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedPujaRoute: typeof AuthenticatedPujaRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedReturnGiftsRoute: typeof AuthenticatedReturnGiftsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSeatingRoute: typeof AuthenticatedSeatingRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedTravelRoute: typeof AuthenticatedTravelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCateringRoute: AuthenticatedCateringRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDanceRoute: AuthenticatedDanceRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedGuestsRoute: AuthenticatedGuestsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedHotelRoute: AuthenticatedHotelRoute,
  AuthenticatedJewelleryRoute: AuthenticatedJewelleryRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMusicRoute: AuthenticatedMusicRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedOutfitsRoute: AuthenticatedOutfitsRoute,
  AuthenticatedPackingRoute: AuthenticatedPackingRoute,
  AuthenticatedPhotoChecklistRoute: AuthenticatedPhotoChecklistRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedPujaRoute: AuthenticatedPujaRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedReturnGiftsRoute: AuthenticatedReturnGiftsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSeatingRoute: AuthenticatedSeatingRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedTravelRoute: AuthenticatedTravelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
